# This Azure pipeline deploys Bundle resources (ML resource config and more)
# defined under sample_project/resources/*
# and sample_project/databricks.yml with staging deployment target configs,
# when PRs are merged into the main branch
name: Bundle Deployment for sample_project Staging

trigger:
  branches:
    include:
      - main

variables:
  - group: databricks-secrets

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: staging
  displayName: 'Deploy to Staging'
  steps:
  - checkout: self

  - script: |
      curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    displayName: 'Install Databricks CLI'

  - script: |
      databricks bundle validate -t staging
    displayName: 'Validate Bundle For Staging'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  - script: |
      databricks bundle deploy -t staging
    displayName: 'Deploy Bundle to Staging'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
