# This Azure pipeline deploys Bundle resources (ML resource config and more)
# defined under sample_project/resources/*
# and sample_project/databricks.yml with dev deployment target configs,
# when PRs are pushed into the dev branch
name: Bundle Deployment for sample_project Dev

trigger:
  branches:
    include:
      - dev

variables:
  - group: databricks-secrets

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: unit_tests
  displayName: 'Run Unit Tests'
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    displayName: 'Use Python 3.10'

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Use JDK 11'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r ../test-requirements.txt
    displayName: 'Install dependencies'
    workingDirectory: './sample_project/'

  - script: |
      pytest
    displayName: 'Run tests with pytest'
    workingDirectory: './sample_project/'

- job: dev
  displayName: 'Deploy to Dev'
  dependsOn: unit_tests
  condition: succeeded()
  steps:
  - checkout: self

  - script: |
      curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    displayName: 'Install Databricks CLI'

  - script: |
      databricks bundle validate -t dev
    displayName: 'Validate Bundle For Dev'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  - script: |
      databricks bundle deploy -t dev
    displayName: 'Deploy Bundle to Dev'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  - script: |
      databricks bundle run write_feature_table_job -t dev
    displayName: 'Run Feature Engineering Workflow for Dev'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  - script: |
      databricks bundle run model_training_job -t dev
    displayName: 'Run Training Workflow for Dev'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
