# This Azure pipeline deploys Bundle resources (ML resource config and more)
# defined under sample_project/resources/*
# and sample_project/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for sample_project Prod

trigger:
  branches:
    include:
      - release

variables:
  - group: databricks-secrets

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: prod
  displayName: 'Deploy to Prod'
  steps:
  - checkout: self

  - script: |
      curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    displayName: 'Install Databricks CLI'

  - script: |
      databricks bundle validate -t prod
    displayName: 'Validate Bundle For Prod'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

  - script: |
      databricks bundle deploy -t prod
    displayName: 'Deploy Bundle to Prod'
    workingDirectory: './sample_project/'
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
