# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under sample_project/resources/*
# and sample_project/databricks.yml with dev deployment target configs,
# when PRs are pushed into the dev branch
name: Bundle Deployment for sample_project Dev

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./sample_project

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  # ARM_TENANT_ID: ${{ secrets.AZURE_SP_TENANT_ID }}
  # ARM_CLIENT_ID: ${{ secrets.AZURE_SP_APPLICATION_ID }}
  # ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
  

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      - name: Run tests with pytest
        run: |
            pytest

  dev:
    needs: unit_tests
    concurrency: sample_project-dev-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.236.0
      - name: Validate Bundle For Dev
        id: validate
        run: |
          databricks bundle validate -t dev
      - name: Deploy Bundle to Dev
        id: deploy
        run: |
          databricks bundle deploy -t dev
      - name: Run Feature Engineering Workflow for Dev
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t dev
      - name: Run Training Workflow for Dev
        id: training
        run: |
          databricks bundle run model_training_job -t dev
